name: sixvalley_delivery_boy
description: A new Flutter application.
publish_to: 'none'
version: 1.0.0+0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get_it: ^7.2.0
  get: ^4.1.4
  http: ^0.13.3
  shared_preferences: ^2.5.1
  dio: ^5.4.0
  geocoding: ^2.0.0
  geolocator: ^13.0.4
  url_launcher: ^6.0.2
  url_strategy: ^0.2.0
  flutter_local_notifications: ^17.2.2
  path_provider: ^2.0.2
  vibration: ^3.1.2
  shimmer: ^2.0.0-nullsafety.0
  flutter_widget_from_html_core: ^0.15.2
  image_picker: ^0.8.0+4
  intl: ^0.18.1
  connectivity_plus: ^5.0.2
  firebase_core: 3.11.0
  firebase_messaging: 15.2.2
  country_code_picker: ^3.2.0
  expandable: ^5.0.1
  custom_map_markers: ^0.0.2+1
  flutter_polyline_points: ^1.0.0
  timeago: ^3.7.0
  dotted_border: ^2.0.0+2
  expandable_bottom_sheet: ^1.1.1+1
  syncfusion_flutter_datepicker: ^23.1.36
  flutter_spinkit: ^5.1.0
  flutter_typeahead: ^4.1.1
  flutter_html: ^3.0.0-alpha.3
  pin_code_fields: ^8.0.1
  readmore: ^2.2.0
  cached_network_image:
  permission_handler: ^11.0.1
  emoji_picker_flutter: ^3.1.0
  file_picker: ^8.1.7
  flutter_downloader: ^1.11.6
  open_file: ^3.5.10
  carousel_slider: ^5.0.0
  image: ^4.0.15
  video_player: ^2.9.2
  chewie: ^1.10.0
  get_thumbnail_video: ^0.7.3
  dotted_line: ^3.2.3




  google_maps_flutter: any
  collection: any
  path: any
  http_parser: any
  flutter_svg: ^2.0.9
dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter_icons:
  android: true
  ios: true
  image_path: "assets/image/app_logo.png"
flutter:

  uses-material-design: true

  assets:
    - assets/icon/
    - assets/image/
    - assets/language/
    - assets/svg/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rubik-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700